### PR TITLE
buck build for 1.1 branch

### PR DESCRIPTION
**Pull request by vgmoose**
mostly the same as https://github.com/buckaroo-pm/nmoinvaz-minizip/commit/2a750715a9217b47ff73f9aeefeeab2903a34cdd for the 1.2 branch, but without a reference to `'aes/*.c'`

### CODE REVIEW

**Comment by njlr** [comment]
So this is `v1.1.0`? I can create a tag for it

**Comment by vgmoose** [comment]
Yes, this is for v1.1 of minizip

**Comment by njlr** [comment]
Tag here: https://github.com/buckaroo-pm/nmoinvaz-minizip/releases/tag/v1.1.0

Use like so: 

```toml
version = "1.1.0"
```

**Comment by vgmoose** [comment]
Previously, I was planning on using: 
```
version = "branch=1.1"
```

If you don't mind me asking, what's the difference between the two?

**Comment by njlr** [comment]
`version = "branch=1.1"` tells Buckaroo to find any commit from the Git branch called `1.1`. 

`version = "1.1"`, `version = "1.1.0"` and `version = "v1.1.0"` tell Buckaroo to find any commit from a tag that parses to semantic-version `1.1.0`. 

In practice, both could result in the same commit. 

More info:

 * https://github.com/LoopPerfect/buckaroo/wiki/Git-as-a-Package-Registry
 * https://github.com/LoopPerfect/buckaroo/wiki/Version-Constraints-DSL

**Pull request merged**
